<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-1I2596E2" name="Default test(failed)" tests="1" failures="1" timestamp="12 May 2020 02:58:53 GMT" time="20.768" errors="0">
  <testcase name="register" time="3.009" classname="may11.Demo2">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.register() didn&amp;apos;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.register() didn't finish within the time-out 3000
	at java.lang.Thread.interrupt(Thread.java:919)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 2 stack frames]]>
    </failure>
  </testcase> <!-- register -->
</testsuite> <!-- Default test(failed) -->
